### ISSUE TITLE
[Question] Dynamic ports

### ISSUE THREAD

**Issue by Frigerius** [sammyfreg/UnrealNetImgui#1]
Hey, do you see a way that the clients can request a port from the server? I mean I could also add a cmd line arg that specifies the port but you can't set per client startup args if you start a game from within UE4 with multiple clients^^
(I also could add my own handling by asking my server which ports to use) But maybe you have smth in mind that you could do on your side :D

**Comment by sammyfreg** [comment]
I offer 2 ways of establishing a connection, Server reaching out to registered clients, or clients reaching out to the server directly.

You can have the client connect directly to the server using `ConnectToApp`  if you know the IP.  (A connection on same PC can use `localhost` for the hostname.)

**Comment by Frigerius** [comment]
Ah ok, I'll give that a shot today, thx :)

**Comment by Frigerius** [comment]
Ah great that works perfect!
