### ISSUE TITLE
UE4.27でFreeType2とのシンボリックエラーが発生する

### ISSUE THREAD

**Issue by Iwanaka** [sammyfreg/UnrealNetImgui#17]
はじめまして。素敵なプラグインありがとうございます。

こちらUnrealEngineのバージョン指定等ございますか？
freetype.libがLNK2019エラーとなりビルドが通らない状態でして、Engine内のFreeType2との互換性が合っていないものと考えています。
ご指摘、ご見解いただければ幸いです。
よろしくお願いします。

環境 : Windows10 UE4.27

![2022-03-20_19h56_44](https://user-images.githubusercontent.com/16041381/159159214-9e60e894-5317-4977-9031-1d83517a5a61.png)

**Comment by sammyfreg** [comment]
WindowsをターゲットにしたUE4.26でテストしています。もしかしたら、あなたがビルドしようとしているプラットフォームでは、Freetypeライブラリがサポートされていないのかもしれませんね :/。
> I have been testing on UE 4.26 targeting Windows. Maybe the Freetype library is not supported on the platform you are trying to build for. :/

Freetype」はUEのデフォルトインストールに存在し、私はそれを使っているだけなので、この特定のエラーについてはよくわかりません。もしかしたら、他の方が遭遇したことがあるかもしれません。とりあえず、'Freetype'のサポートを無効にすることができます。フォントの品質が少し落ちますが、それ以外はまったく同じように動作します。
> 'Freetype' is present in the default UE installation and I am just using it, so I am unsure about this particular error. Maybe some other people have encountered it before. For now, you can disable 'Freetype' support. It reduce the font quality a little bit, but otherwise works exactly the same.

in _UnrealNetImgui\Source\NetImgui.Build.cs : 85_
```
    // bool bFreeType_Enabled = true;
    bool bFreeType_Enabled = false;
```

**Comment by Iwanaka** [comment]
回答ありがとうございます。

そうですね、私だけの環境かもしれませんが、どうやら4.27ではFreeTypeのバージョン違いなのかUE4内のFreeTypeと互換性が無いように見受けられました。

いただいた内容で無事動作させることができました。
ありがとうございます。

**Comment by sammyfreg** [comment]
この問題を他のユーザーにも知ってもらうために、ドキュメントを更新しました。ご報告ありがとうございました。
> I updated the documentation to let other users know about this problem. Thank you for the report.
