### ISSUE TITLE
ImUnrealCommand: Non editor builds don't have IConsoleCommandExecutor

### ISSUE THREAD

**Issue by GBS3D** [sammyfreg/UnrealNetImgui#19]
I have checked it in a console build. I changed it to use GEngine->GameViewport->ViewportConsole in the meantime so it works

**Comment by sammyfreg** [comment]
Thank you, I will take a look.

**Comment by sammyfreg** [comment]
Thank you for bringing this to my attention, I don't have access to console SDK at home, and never noticed it. Hopefully, my latest push to the Dev branch should take care of it (7a55819b55c6218cb254fd764fadc8e038a861ec).
