### ISSUE TITLE
Multiple errors depending on the plugin directory.

### ISSUE THREAD

**Issue by mandox713** [sammyfreg/UnrealNetImgui#21]
I followed the instructions from the readme, added the dependencies in .build.cs and everything, but if I put the plugin folder in (**Engine/Plugins**) it gives this exact error:

**1.**
**Expecting to find a type to be declared in a module rules named 'NetImgui' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.**

If I put the plugin folder in (**Project/Plugins**):

**2.**
![image](https://user-images.githubusercontent.com/92693267/192914452-bc4b71b8-748b-40c0-8549-27b4983ff097.png)
**27 unresolved externals**

If I put the plugin folder in (**Engine/Plugins/Marketplace**):

**3.**
![image](https://user-images.githubusercontent.com/92693267/192914639-9229558a-56f8-4590-ad78-3cd2bc5c7009.png)

Even after **I recompiled** the plugin using **RunUAT.**

Making it impossible to use, 
I tested 2 versions 1.10 and 1.09, the result was the same.
My unreal version is **5.0.3**

**Comment by sammyfreg** [comment]
I never looked into how the Marketplace works and its requirement, so I've
always tested as a developer compiling locally, with the plugin in (
*Project/Plugins*) or (*Engine/Plugins*).

Would you mind telling me which version of UE5 are you using?

**Comment by Spidey1618** [comment]
it's 5.0.2

**Comment by exymma** [comment]
> I never looked into how the Marketplace works and its requirement, so I've always tested as a developper compiling locally, with the plugin in ( *Project/Plugins*) or (*Engine/Plugins*). Would you mind telling me which version of UE5 are you using?

it's 5.0.3

**Comment by sammyfreg** [comment]
I will try having a look this weekend after installing UE5 on my new PC.

**Comment by exymma** [comment]
> I will try havign a look this weekend after installing UE5 on my new PC.

Ok.

**Comment by sammyfreg** [comment]
Ok, I figured out the cause of the issue. I optionally activate Dear ImGui _Freetype_ support, using the UE _Freetype_ plugin, but it seems to not be linking properly at the moment. This is purely optional, helping to generate a better-looking font. 

To get around the issue for now, disable 'Freetype' support :

Leave the UnrealNetImgui plugin in your project plugins folder and in `Plugins\UnrealNetImgui\Source\NetImgui.Build.cs : 85`, change the value of `bFreeType_Enabled` to **false** .

**Comment by sammyfreg** [comment]
I believe my latest push in the dev branch, fix the issue properly (05a14b17ce0a77de03f6f86414c162146be69fbc). 

Could you confirm? I was missing dependency on _libpng_ and _zlib_ when _Freetype_ is active, thinking they were automatically pulled.

**Comment by exymma** [comment]
> I believe my latest push in the dev branch, fix the issue properly ([05a14b1](https://github.com/sammyfreg/UnrealNetImgui/commit/05a14b17ce0a77de03f6f86414c162146be69fbc)).
> 
> Could you confirm? I was missing dependency on _libpng_ and _zlib_ when _Freetype_ is active, thinking they were automatically pulled.

As soon as I can, I'll do a test
