### ISSUE TITLE
Intermittent shutdown crashes

### ISSUE THREAD

**Issue by rtjonnyr** [sammyfreg/UnrealNetImgui#6]
During application shutdown there is a race between DestroyModule and the thread that runs CommunicationsHost.

There is a clumsy, temporary fix at https://github.com/sammyfreg/UnrealNetImgui/pull/5 but it would be good to find something better. Perhaps there should be a mutex at the ClientInfo level?

**Comment by sammyfreg** [comment]
I will try to pin point the issue. Hopefully, it is only related to the listening socket, since I had something in place to prevent race condition with the connection socket (using atomic state).

**Comment by rtjonnyr** [comment]
I believe it is only related to the listening socket. Let me get a partial callstack.

**Comment by rtjonnyr** [comment]
It was a null pointer deference (mpSocket was null, not pListenSocket) at the following line in ListenConnect() in NetImgui_NetworkUE4.cpp:

`FSocket* pNewSocket = pListenSocket->mpSocket->Accept(FString("netImgui"));`

My hypothesis was that this code was running at the same time as Disconnect() in the same file was called on the thread running the module shutdown. Adding a sleep to address the 100% core issue will have dramatically reduced the chances of this recurring. It seemed to occur ~10% of shutdowns prior to the sleep being added, when ListenConnect() was running constantly.

**Comment by rtjonnyr** [comment]
FWIW I cannot repro with https://github.com/sammyfreg/UnrealNetImgui/commit/2f4737522b93733f063e8374f3262f8927e60b32. happy to close.
